const $ = (id) => document.getElementById(id);
const LS = {
  name: 'xfx_v28_name',
  archives: 'xfx_v28_archives',
  projectNotes: 'xfx_v28_project_notes',
  settings: 'xfx_v28_settings',
  draft: 'xfx_v28_draft',
  files: 'xfx_v28_files'
};
const presets = {
  replace: ['更换前正面：拍 1 张，设备正面要清楚。','更换中：拍 1 张，尽量带上吊车/叉车/材料。','更换后正常运行正面：拍 1 张，运行状态要看得出来。'].join('\n'),
  repair: ['每台机器 2 张：','1、内部技改/维修照片。','2、串号照片。'].join('\n'),
  batch: '每台机器 1 张：机器正常运行照片或串号照片。',
  install: '每天至少 1 张：含科华设备的现场施工照片。',
  day: ['入场：拍 1 张含设备屏幕或操作过程的照片。','离场：拍 1 张含设备屏幕或操作过程的照片。','收工前补齐，别让月底表格像没来过。'].join('\n')
};
let alarmInterval = null, alarmTimeouts = [], alarmAudioCtx = null, alarmOsc = [], deferredPrompt = null;
let selectedWatermarkImages = [], selectedChecklistImages = [], bfImages = [], pendingExport = null;
let parsedItems = [];

function todayStr(){ return new Date().toISOString().slice(0,10); }
function currentMonth(){ return new Date().toISOString().slice(0,7); }
function timeNow(){ const d=new Date(); return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; }
function load(key, fallback){ try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch(e){return fallback} }
function save(key, value){ localStorage.setItem(key, JSON.stringify(value)); }
function currentName(){ return localStorage.getItem(LS.name) || ''; }
function getArchives(){ return load(LS.archives, []); }
function setArchives(v){ save(LS.archives, v); refreshHistory(); refreshExportProjects(); }
function getFiles(){ return load(LS.files, []); }
function setFiles(v){ save(LS.files, v); refreshFileList(); }
function getNotes(){ return load(LS.projectNotes, {}); }
function setNotes(v){ save(LS.projectNotes, v); }
function getSettings(){ return load(LS.settings, {start:'08:30', middle:'14:00', end:'18:00'}); }
function setSettings(v){ save(LS.settings, v); }
function setName(n){ const val=(n||'').trim(); localStorage.setItem(LS.name,val); if($('settingsName')) $('settingsName').value=val; if($('servicePerson')) $('servicePerson').value=val; if($('subtitle')) $('subtitle').textContent=`${val || '兄弟'} · 今日填报 · 历史补录 · 月底出表`; }
function isImageFile(f){ return !!f && (f.data || ((f.type||'').startsWith('image/') || /\.(jpg|jpeg|png|gif|webp|bmp|heic|heif)$/i.test(f.name||''))); }
function escapeHtml(s){ return (s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function nl2br(s){ return escapeHtml(s).replace(/\n/g,'<br>'); }
function safeName(s){ return (s||'项目').replace(/[\\/:*?"<>|]/g,'_'); }
function formatDateCN(v){ return v || ''; }
function monthCN(m){ if(!m) return `${new Date().getFullYear()}年${new Date().getMonth()+1}月份`; const [y,mm]=m.split('-'); return `${y}年${Number(mm)}月份`; }
function monthMatch(date, m){ return !m || (date||'').slice(0,7)===m; }

function init(){
  startSplash();
  $('workDate').value=todayStr(); $('bfWorkDate').value=todayStr(); $('exportMonth').value=currentMonth();
  const n=currentName();
  if(!n) $('nameGate').classList.remove('hidden'); else { $('servicePerson').value=n; $('settingsName').value=n; setName(n); }
  const s=getSettings(); $('startTime').value=s.start; $('middleTime').value=s.middle; $('endTime').value=s.end;
  bindEvents(); restoreDraft(); refreshHistory(); refreshExportProjects(); refreshFileList(); startAlarmLoop(); registerSW();
}
function startSplash(){ const splash=$('splashScreen'); if(!splash) return; setTimeout(()=>{splash.classList.add('hide'); setTimeout(()=>splash.remove(),520);},2400); }

function bindEvents(){
  document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>switchTab(btn.dataset.tab)));
  window.addEventListener('beforeinstallprompt', e=>{e.preventDefault(); deferredPrompt=e;});
  window.addEventListener('appinstalled',()=>{deferredPrompt=null; toast('已装到桌面');});
  $('installBtn').addEventListener('click', handleInstallClick);
  $('saveGateName').addEventListener('click',()=>{ const v=$('gateName').value.trim(); if(!v) return toast('先写名字'); setName(v); $('nameGate').classList.add('hidden'); requestNotify(); unlockAudio(); startAlarmLoop(); });
  $('saveName').addEventListener('click',()=>{ const v=$('settingsName').value.trim(); if(!v) return toast('先写名字'); setName(v); saveDraft(); toast('名字存好了'); });
  $('saveProject').addEventListener('click',()=>{ saveDraft(); saveAlarmSettings(); requestNotify(); unlockAudio(); toast('项目和提醒存好了'); });
  ['projectName','city','servicePerson','workDate','workContent','pendingIssues','nextPlan','photoNotes'].forEach(id=>$(id).addEventListener('input',saveDraft));
  $('projectName').addEventListener('input',loadProjectNotes);
  ['startTime','middleTime','endTime'].forEach(id=>$(id).addEventListener('change',()=>{ saveAlarmSettings(); saveDraft(); }));
  $('presetSelect').addEventListener('change',()=>{ if(presets[$('presetSelect').value]) $('photoNotes').value=presets[$('presetSelect').value]; saveDraft(); });
  $('savePhotoNotes').addEventListener('click',()=>{ saveProjectNotes(); toast('拍照要求存好了'); });
  $('watermarkPhotos').addEventListener('change',()=>handlePhotoSelect('watermarkPhotos','photoPreview','watermark'));
  $('checklistPhotos').addEventListener('change',()=>handlePhotoSelect('checklistPhotos','checklistPreview','checklist'));
  $('openCamera').addEventListener('click',openWatermarkCamera); $('openCameraTop').addEventListener('click',openWatermarkCamera);
  $('copyLastContent').addEventListener('click',copyLastArchiveContent);
  $('copyWechat').addEventListener('click',showReportModal);
  $('copyReportText').addEventListener('click',copyReportTextNow);
  $('openWechatOnly').addEventListener('click',openWechat);
  $('closeReportModal').addEventListener('click',()=>$('reportModal').classList.add('hidden'));
  $('saveArchive').addEventListener('click',saveArchive);
  $('clearToday').addEventListener('click',clearTodayForm); $('clearTodayTop').addEventListener('click',clearTodayForm);
  $('parsePaste').addEventListener('click',parsePasteText); $('clearParsed').addEventListener('click',()=>{parsedItems=[]; renderParsedList();});
  $('bfPhotos').addEventListener('change',()=>handleBackfillPhotos()); $('saveBackfill').addEventListener('click',saveManualBackfill);
  $('historySearch').addEventListener('input',refreshHistory);
  $('saveFiles').addEventListener('click',saveFileCabinetFiles); $('fileSearch').addEventListener('input',refreshFileList);
  $('exportCurrent').addEventListener('click',()=>exportProject($('exportProject').value)); $('exportAll').addEventListener('click',exportAllProjects);
  $('closeExportModal').addEventListener('click',closeExportModal); $('cancelExport').addEventListener('click',closeExportModal); $('confirmExport').addEventListener('click',confirmExportDownload);
  $('enableAlarm').addEventListener('click',async()=>{ await requestNotify(); unlockAudio(); saveAlarmSettings(); await fireNotification('闹钟开了','只要手机没杀后台，到点就会提醒。'); triggerAlarm('测试报警','听到没？这就是防漏拍专用嗓门。'); });
  $('testAlarm').addEventListener('click',()=>{ unlockAudio(); triggerAlarm('测试报警','正在试嗓子，点停止报警就停。'); });
  $('testBgAlarm').addEventListener('click',async()=>{ await requestNotify(); toast('10秒后叫你一声，可以切出去试试。'); setTimeout(()=>{ fireNotification('后台提醒测试','你能看到这条，说明提醒能跑。'); triggerAlarm('后台提醒测试','后台测试到了。');},10000); });
  $('stopAlarm').addEventListener('click',stopAlarm);
  $('clearAll').addEventListener('click',()=>{ if(!confirm('确定清空本机全部数据？')) return; Object.values(LS).forEach(k=>localStorage.removeItem(k)); selectedWatermarkImages=[]; selectedChecklistImages=[]; bfImages=[]; parsedItems=[]; ['projectName','city','servicePerson','workContent','pendingIssues','nextPlan','photoNotes','pasteText','bfProjectName','bfCity','bfWorkContent','bfPendingIssues','bfNextPlan','fileProject','fileRemark'].forEach(id=>{ if($(id)) $(id).value=''; }); $('workDate').value=todayStr(); $('bfWorkDate').value=todayStr(); renderPhotoPreview('photoPreview','watermark'); renderPhotoPreview('checklistPreview','checklist'); renderBackfillPreview(); renderParsedList(); refreshHistory(); refreshExportProjects(); refreshFileList(); toast('清干净了'); });
  document.addEventListener('visibilitychange',()=>{ if(!document.hidden) checkAlarm(true); }); window.addEventListener('focus',()=>checkAlarm(true)); window.addEventListener('pageshow',()=>checkAlarm(true)); window.addEventListener('beforeunload',saveDraft);
  document.addEventListener('input',()=>{ clearTimeout(window.__xfxDraftTimer); window.__xfxDraftTimer=setTimeout(saveDraft,250); },true);
}
function switchTab(tab){ document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===tab)); }
function toast(msg){ let box=$('xfxToast'); if(!box){ box=document.createElement('div'); box.id='xfxToast'; box.className='xfxToast'; document.body.appendChild(box); } box.textContent=msg; box.classList.add('show'); clearTimeout(window.__toastTimer); window.__toastTimer=setTimeout(()=>box.classList.remove('show'),2300); }
function isStandaloneMode(){ return matchMedia('(display-mode: standalone)').matches || window.navigator.standalone===true; }
function isIOSDevice(){ return /iphone|ipad|ipod/i.test(navigator.userAgent) || (navigator.platform==='MacIntel' && navigator.maxTouchPoints>1); }
async function handleInstallClick(){ if(isStandaloneMode()) return toast('已经是桌面模式'); if(deferredPrompt){ deferredPrompt.prompt(); try{await deferredPrompt.userChoice;}catch(e){} deferredPrompt=null; return; } const ua=navigator.userAgent.toLowerCase(); if(ua.includes('micromessenger')) return toast('微信里点右上角 ···，选在浏览器打开'); if(isIOSDevice()) return toast('苹果用 Safari：分享 → 添加到主屏幕'); toast('安卓点浏览器菜单：添加到桌面 / 安装应用'); }

function collectForm(){ return { projectName:$('projectName').value.trim(), city:$('city').value.trim(), servicePerson:$('servicePerson').value.trim()||currentName(), workDate:$('workDate').value, startTime:$('startTime').value, middleTime:$('middleTime').value, endTime:$('endTime').value, workContent:$('workContent').value.trim(), pendingIssues:$('pendingIssues').value.trim(), nextPlan:$('nextPlan').value.trim(), photoNotes:$('photoNotes').value.trim() }; }
function saveDraft(){ const d={...collectForm(), watermarkImages:selectedWatermarkImages, checklistImages:selectedChecklistImages}; try{ save(LS.draft,d); }catch(e){ toast('草稿保存失败，照片可能太多'); } }
function restoreDraft(){ const d=load(LS.draft,null); if(!d) return; ['projectName','city','servicePerson','workDate','startTime','middleTime','endTime','workContent','pendingIssues','nextPlan','photoNotes'].forEach(id=>{ if(d[id]!==undefined && d[id]!==null) $(id).value=d[id]; }); selectedWatermarkImages=Array.isArray(d.watermarkImages)?d.watermarkImages:[]; selectedChecklistImages=Array.isArray(d.checklistImages)?d.checklistImages:[]; renderPhotoPreview('photoPreview','watermark'); renderPhotoPreview('checklistPreview','checklist'); }
function loadProjectNotes(){ const p=$('projectName').value.trim(); if(!p) return; const notes=getNotes(); if(notes[p]) $('photoNotes').value=notes[p]; saveDraft(); }
function saveProjectNotes(){ const p=$('projectName').value.trim(); if(!p) return toast('项目名先写上'); const notes=getNotes(); notes[p]=$('photoNotes').value.trim(); setNotes(notes); }
function saveAlarmSettings(){ setSettings({start:$('startTime').value,middle:$('middleTime').value,end:$('endTime').value}); startAlarmLoop(); }

function photoArray(kind){ return kind==='watermark'?selectedWatermarkImages:selectedChecklistImages; }
async function handlePhotoSelect(inputId, boxId, kind){ const input=$(inputId), files=[...input.files].filter(isImageFile); if(!files.length){ input.value=''; return; } toast(`正在加入 ${files.length} 张照片`); const group=kind==='watermark'?'今日水印照片':'项目服务清单照片'; const imgs=[]; for(const f of files){ imgs.push(await compressImageFile(f,group)); } if(kind==='watermark') selectedWatermarkImages.push(...imgs); else selectedChecklistImages.push(...imgs); input.value=''; renderPhotoPreview(boxId,kind); saveDraft(); toast(`已加 ${imgs.length} 张，共 ${photoArray(kind).length} 张`); }
function renderPhotoPreview(boxId, kind){ const box=$(boxId); if(!box) return; const arr=photoArray(kind); box.innerHTML=''; arr.forEach((im,idx)=>{ const item=document.createElement('div'); item.className='previewItem'; item.innerHTML=`<img src="${im.data}" alt="${escapeHtml(im.name||'照片')}"><small>${idx+1}/${arr.length}</small>`; const btn=document.createElement('button'); btn.type='button'; btn.className='removePhoto'; btn.textContent='×'; btn.onclick=()=>{ arr.splice(idx,1); renderPhotoPreview(boxId,kind); saveDraft(); }; item.appendChild(btn); box.appendChild(item); }); }
function compressImageFile(file, group){ return new Promise((resolve,reject)=>{ const reader=new FileReader(); reader.onerror=reject; reader.onload=()=>{ const img=new Image(); img.onerror=reject; img.onload=()=>{ const max=900; let w=img.width,h=img.height; if(Math.max(w,h)>max){ const r=max/Math.max(w,h); w=Math.round(w*r); h=Math.round(h*r); } const canvas=document.createElement('canvas'); canvas.width=w; canvas.height=h; canvas.getContext('2d').drawImage(img,0,0,w,h); const data=canvas.toDataURL('image/jpeg',0.62); resolve({name:file.name,group,data,w,h}); }; img.src=reader.result; }; reader.readAsDataURL(file); }); }
function dataURLToFile(dataUrl, filename){ const arr=dataUrl.split(','), mime=(arr[0].match(/:(.*?);/)||[])[1]||'image/jpeg', bin=atob(arr[1]||''); const u8=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) u8[i]=bin.charCodeAt(i); return new File([u8],filename||'photo.jpg',{type:mime}); }
function allImages(item){ return [...(item.watermarkImages||[]),...(item.checklistImages||[]),...(item.images||[])]; }

function reportText(d=collectForm()){ return `项目名称：${d.projectName||''}\n省份/城市：${d.city||''}\n\n日期：${formatDateCN(d.workDate)}\n\n工作内容：\n${d.workContent||''}\n\n待处理问题：\n${d.pendingIssues||''}\n\n次日计划：\n${d.nextPlan||''}`; }
function showReportModal(){ saveDraft(); const text=reportText(); $('reportTextArea').value=text; $('reportModal').classList.remove('hidden'); setTimeout(()=>{ $('reportTextArea').focus(); $('reportTextArea').select(); copyReportTextNow(false); },60); }
async function copyReportTextNow(showToast=true){ const text=$('reportTextArea').value || reportText(); let ok=false; try{ if(navigator.clipboard && window.isSecureContext){ await navigator.clipboard.writeText(text); ok=true; } }catch(e){} if(!ok) ok=fallbackCopy(text); if(showToast) toast(ok?'文本复制好了':'自动复制没成，长按文本手动复制'); return ok; }
function fallbackCopy(text){ const ta=document.createElement('textarea'); ta.value=text; ta.style.position='fixed'; ta.style.left='-9999px'; document.body.appendChild(ta); ta.focus(); ta.select(); let ok=false; try{ ok=document.execCommand('copy'); }catch(e){} ta.remove(); return ok; }
function openWechat(){ location.href='weixin://'; setTimeout(()=>{ location.href='intent://#Intent;scheme=weixin;package=com.tencent.mm;end'; },500); }
function openWatermarkCamera(){ const tries=['xhey://','xhey://camera','xhey://watermark_camera','intent://#Intent;scheme=xhey;package=com.xhey.xcamera;end']; let i=0; const go=()=>{ if(i>=tries.length) return; location.href=tries[i++]; if(i<tries.length) setTimeout(go,650); }; go(); }
function copyLastArchiveContent(){ const list=getArchives(); if(!list.length) return toast('还没历史记录，先存一次'); const last=list[0]; $('workContent').value=last.workContent||''; $('pendingIssues').value=last.pendingIssues||''; $('nextPlan').value=last.nextPlan||''; saveDraft(); toast('上一条内容搬过来了'); }
async function saveArchive(){ const d=collectForm(); if(!d.projectName) return toast('项目名称先写上'); if(!d.workContent) return toast('工作内容先写点'); saveProjectNotes(); saveAlarmSettings(); const item={...d,id:Date.now(),createdAt:new Date().toISOString(),watermarkImages:[...selectedWatermarkImages],checklistImages:[...selectedChecklistImages]}; try{ const list=getArchives(); list.unshift(item); setArchives(list); saveDraft(); toast('归档好了，不点清除就一直保留'); }catch(e){ toast('归档失败，照片可能太多'); } }
function clearTodayForm(){ if(!confirm('真要清今天写的内容和照片？项目名称、城市、时间、拍照说明会留着。')) return; ['workContent','pendingIssues','nextPlan'].forEach(id=>$(id).value=''); selectedWatermarkImages=[]; selectedChecklistImages=[]; $('watermarkPhotos').value=''; $('checklistPhotos').value=''; renderPhotoPreview('photoPreview','watermark'); renderPhotoPreview('checklistPreview','checklist'); saveDraft(); toast('今日填写清掉了'); }

function parseLabel(text,label,nextLabels){ const re=new RegExp(label+'\\s*[：:]\\s*','i'); const m=re.exec(text); if(!m) return ''; const start=m.index+m[0].length; let end=text.length; for(const n of nextLabels){ const r=new RegExp('\\n\\s*'+n+'\\s*[：:]','i'); const mm=r.exec(text.slice(start)); if(mm) end=Math.min(end,start+mm.index); } return text.slice(start,end).trim(); }
function parsePasteText(){ const raw=$('pasteText').value.trim(); if(!raw) return toast('先把以前发过的内容粘进来'); const normalized=raw.replace(/\r/g,''); const baseProject=parseLabel(normalized,'项目名称',['省份/城市','日期','工作内容','待处理问题','次日计划']); const baseCity=parseLabel(normalized,'省份/城市',['项目名称','日期','工作内容','待处理问题','次日计划']); const dateMatches=[...normalized.matchAll(/(?:^|\n)\s*日期\s*[：:]\s*([^\n]+)/g)]; const items=[]; if(dateMatches.length){ dateMatches.forEach((m,idx)=>{ const start=m.index; const end=idx+1<dateMatches.length?dateMatches[idx+1].index:normalized.length; const block=normalized.slice(start,end); const before=normalized.slice(0,start); const project=parseLabel(block,'项目名称',['省份/城市','日期','工作内容','待处理问题','次日计划'])||baseProject||parseLabel(before,'项目名称',['省份/城市','日期','工作内容']); const city=parseLabel(block,'省份/城市',['项目名称','日期','工作内容','待处理问题','次日计划'])||baseCity||parseLabel(before,'省份/城市',['项目名称','日期','工作内容']); const item={projectName:project, city, workDate:(m[1]||'').trim(), workContent:parseLabel(block,'工作内容',['待处理问题','次日计划','项目名称','日期']), pendingIssues:parseLabel(block,'待处理问题',['次日计划','项目名称','日期']), nextPlan:parseLabel(block,'次日计划',['项目名称','日期'])}; if(item.projectName||item.workContent) items.push(normalizeParsedItem(item)); }); } else { const item={projectName:baseProject, city:baseCity, workDate:parseLabel(normalized,'日期',['工作内容','待处理问题','次日计划']), workContent:parseLabel(normalized,'工作内容',['待处理问题','次日计划']), pendingIssues:parseLabel(normalized,'待处理问题',['次日计划']), nextPlan:parseLabel(normalized,'次日计划',[])}; if(item.projectName||item.workContent) items.push(normalizeParsedItem(item)); }
  parsedItems=items; renderParsedList(); toast(items.length?`识别到 ${items.length} 条，确认后保存`:'没识别出来，检查格式'); }
function normalizeParsedItem(x){ const d=(x.workDate||'').replace(/[年月.\/]/g,'-').replace(/日/g,'').trim(); return {...x, workDate:d || todayStr(), servicePerson:currentName(), watermarkImages:[], checklistImages:[]}; }
function renderParsedList(){ const box=$('parsedList'); if(!parsedItems.length){ box.className='parsedList empty'; box.textContent='还没识别内容'; return; } box.className='parsedList'; box.innerHTML=''; parsedItems.forEach((it,idx)=>{ const div=document.createElement('div'); div.className='parsedItem'; div.innerHTML=`<strong>${escapeHtml(it.projectName||'未识别项目')} · ${escapeHtml(it.workDate||'未识别日期')}</strong><small>${escapeHtml(it.city||'')}</small><p>${nl2br(it.workContent||'')}</p><div class="parsedActions"><button class="secondary" data-save="${idx}">保存这条</button><button class="danger light" data-del="${idx}">删除</button></div>`; box.appendChild(div); }); box.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveParsedItem(Number(b.dataset.save))); box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{parsedItems.splice(Number(b.dataset.del),1); renderParsedList();}); }
function saveParsedItem(idx){ const it=parsedItems[idx]; if(!it) return; if(!it.projectName) return toast('这条没项目名，先删了重识别或手动补'); const item={...it,id:Date.now()+idx,createdAt:new Date().toISOString()}; const list=getArchives(); list.unshift(item); setArchives(list); parsedItems.splice(idx,1); renderParsedList(); toast('补录已保存'); }
async function handleBackfillPhotos(){ const files=[...$('bfPhotos').files].filter(isImageFile); if(!files.length){ $('bfPhotos').value=''; return; } const imgs=[]; for(const f of files) imgs.push(await compressImageFile(f,'补录照片')); bfImages.push(...imgs); $('bfPhotos').value=''; renderBackfillPreview(); toast(`补录照片已加 ${imgs.length} 张`); }
function renderBackfillPreview(){ const box=$('bfPhotoPreview'); box.innerHTML=''; bfImages.forEach((im,idx)=>{ const item=document.createElement('div'); item.className='previewItem'; item.innerHTML=`<img src="${im.data}"><small>${idx+1}/${bfImages.length}</small>`; const btn=document.createElement('button'); btn.type='button'; btn.className='removePhoto'; btn.textContent='×'; btn.onclick=()=>{bfImages.splice(idx,1); renderBackfillPreview();}; item.appendChild(btn); box.appendChild(item); }); }
function saveManualBackfill(){ const item={id:Date.now(),createdAt:new Date().toISOString(),projectName:$('bfProjectName').value.trim(),city:$('bfCity').value.trim(),servicePerson:currentName(),workDate:$('bfWorkDate').value,workContent:$('bfWorkContent').value.trim(),pendingIssues:$('bfPendingIssues').value.trim(),nextPlan:$('bfNextPlan').value.trim(),watermarkImages:[...bfImages],checklistImages:[]}; if(!item.projectName) return toast('项目名先写上'); if(!item.workContent) return toast('工作内容先写点'); const list=getArchives(); list.unshift(item); setArchives(list); bfImages=[]; renderBackfillPreview(); ['bfWorkContent','bfPendingIssues','bfNextPlan'].forEach(id=>$(id).value=''); toast('补录保存好了'); }

function refreshHistory(){ const box=$('historyList'); const q=($('historySearch')?.value||'').trim().toLowerCase(); let list=getArchives(); if(q) list=list.filter(it=>[it.projectName,it.city,it.workDate,it.workContent,it.pendingIssues,it.nextPlan].some(v=>(v||'').toLowerCase().includes(q))); if(!list.length){ box.className='list empty'; box.textContent=q?'没搜到记录':'暂无归档记录'; return; } box.className='list'; box.innerHTML=''; list.forEach(item=>{ const imgs=allImages(item); const thumbs=imgs.slice(0,6).map(im=>`<span class="photoMini"><img src="${im.data}" alt="照片"></span>`).join(''); const div=document.createElement('div'); div.className='historyItem'; div.innerHTML=`<strong>${escapeHtml(item.projectName)} · ${escapeHtml(item.workDate)}</strong><small>${escapeHtml(item.city||'')} ｜ 图片 ${imgs.length} 张</small><p>${nl2br(item.workContent||'')}</p><div class="historyPhotos">${thumbs}</div><div class="historyActions"><button data-copy="${item.id}" class="secondary">复制汇报</button><button data-del="${item.id}" class="danger light">删除</button></div><div class="moduleDev">开发者：昆明彭于晏</div>`; box.appendChild(div); }); box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyHistory(Number(b.dataset.copy))); box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteHistory(Number(b.dataset.del))); }
function copyHistory(id){ const item=getArchives().find(x=>x.id===id); if(!item) return; $('reportTextArea').value=reportText(item); $('reportModal').classList.remove('hidden'); setTimeout(()=>{ $('reportTextArea').focus(); $('reportTextArea').select(); copyReportTextNow(); },60); }
function deleteHistory(id){ if(!confirm('这条真删？')) return; setArchives(getArchives().filter(x=>x.id!==id)); }
function refreshExportProjects(){ const select=$('exportProject'); const projects=[...new Set(getArchives().map(x=>x.projectName).filter(Boolean))]; select.innerHTML=projects.length?projects.map(p=>`<option value="${escapeHtml(p)}">${escapeHtml(p)}</option>`).join(''):'<option value="">暂无项目</option>'; }

function exportRows(project){ const m=$('exportMonth').value; return getArchives().filter(x=>x.projectName===project && monthMatch(x.workDate,m)); }
function exportProject(project){ if(!project) return toast('暂无项目'); const rows=exportRows(project); if(!rows.length) return toast('这个项目这个月份没记录'); openExportPreview(rows,project,$('exportMonth').value); }
function exportAllProjects(){ const projects=[...new Set(getArchives().map(x=>x.projectName).filter(Boolean))]; if(!projects.length) return toast('暂无项目'); const m=$('exportMonth').value; const usable=projects.map(p=>({p,rows:getArchives().filter(x=>x.projectName===p && monthMatch(x.workDate,m))})).filter(x=>x.rows.length); if(!usable.length) return toast('这个月份没有可导出的项目'); if(!confirm(`将导出 ${usable.length} 个项目，确定？`)) return; usable.forEach((x,i)=>setTimeout(()=>downloadHTMLReport(x.rows,x.p,m),i*350)); }
function openExportPreview(rows, project, month){ pendingExport={rows,project,month}; $('exportPreviewTitle').textContent=`${project} ${monthCN(month)}工作汇总`; $('exportPreviewBox').innerHTML=buildMiniTable(rows); $('exportModal').classList.remove('hidden'); }
function closeExportModal(){ $('exportModal').classList.add('hidden'); pendingExport=null; }
function confirmExportDownload(){ if(!pendingExport) return; downloadHTMLReport(pendingExport.rows,pendingExport.project,pendingExport.month); closeExportModal(); }
function buildMiniTable(rows){ const ordered=[...rows].sort((a,b)=>(a.workDate||'').localeCompare(b.workDate||'')); return `<table class="miniTable"><thead><tr><th>项目名称</th><th>日期</th><th>工作内容</th><th>图片</th></tr></thead><tbody>${ordered.map(r=>`<tr><td>${escapeHtml(r.projectName||'')}</td><td>${escapeHtml(r.workDate||'')}</td><td>${nl2br(r.workContent||'')}</td><td>${allImages(r).slice(0,8).map(im=>`<img class="miniPic" src="${im.data}">`).join('')||'无图'}</td></tr>`).join('')}</tbody></table>`; }
function buildReportHTML(rows, project, month){ const ordered=[...rows].sort((a,b)=>(a.workDate||'').localeCompare(b.workDate||'')); const title=`${project} ${monthCN(month)}工作汇总`; const trs=ordered.map(r=>`<tr><td data-label="项目名称">${escapeHtml(r.projectName||'')}</td><td data-label="日期">${escapeHtml(r.workDate||'')}</td><td data-label="工作内容">${nl2br(r.workContent||'')}</td><td data-label="图片" class="photoCell">${allImages(r).map(im=>`<figure><img src="${im.data}"><figcaption>${escapeHtml(im.group||'照片')}</figcaption></figure>`).join('')||'<span class="muted">无图</span>'}</td></tr>`).join(''); return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>body{margin:0;background:#f3f6fb;font-family:Arial,'Microsoft YaHei',sans-serif;color:#111827;padding:18px}.report{max-width:1120px;margin:auto;background:#fff;border-radius:18px;padding:22px;box-shadow:0 10px 28px rgba(20,40,80,.08)}h1{text-align:center;margin:0 0 18px;font-size:24px}table{border-collapse:collapse;width:100%;min-width:760px}th,td{border:1px solid #94a3b8;padding:10px;vertical-align:top;font-size:14px}th{background:#eff6ff}.wrap{overflow:auto;border-radius:12px}td:nth-child(3){line-height:1.8}.photoCell figure{display:inline-block;margin:5px;text-align:center;color:#6b7280;font-size:11px}.photoCell img{width:150px;max-height:210px;object-fit:contain;border:1px solid #cbd5e1;border-radius:8px}.dev{text-align:right;color:#6b7280;font-size:12px;margin-top:14px}@media(max-width:700px){body{padding:10px}.report{padding:12px}h1{font-size:20px}.wrap{overflow:visible}table{min-width:0}thead{display:none}tr,td{display:block;width:100%}tr{border:1px solid #94a3b8;border-radius:14px;margin:12px 0;overflow:hidden}td{border:0;border-bottom:1px dashed #d6dee9}td:before{content:attr(data-label);display:block;color:#1d4ed8;font-weight:900;margin-bottom:5px}.photoCell img{width:calc(50vw - 42px);max-height:180px}}</style></head><body><main class="report"><h1>${escapeHtml(title)}</h1><div class="wrap"><table><thead><tr><th>项目名称</th><th>日期</th><th>工作内容</th><th>图片</th></tr></thead><tbody>${trs}</tbody></table></div><div class="dev">开发者：昆明彭于晏</div></main></body></html>`; }
function downloadHTMLReport(rows, project, month){ const html=buildReportHTML(rows,project,month); const blob=new Blob(['\ufeff'+html],{type:'text/html;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`${safeName(project)}_${monthCN(month)}工作汇总.html`; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),60000); }

async function saveFileCabinetFiles(){ const files=[...$('fileUpload').files]; if(!files.length) return toast('先选文件'); const project=$('fileProject').value.trim(), category=$('fileCategory').value, remark=$('fileRemark').value.trim(); const arr=getFiles(); for(const f of files){ if(f.size>5*1024*1024){ toast(`${f.name} 太大，先不存本机`); continue; } const data=await readFileDataURL(f); arr.unshift({id:Date.now()+Math.random(),name:f.name,type:f.type||'文件',size:f.size,project,category,remark,createdAt:new Date().toISOString(),data}); } setFiles(arr); $('fileUpload').value=''; toast('文件已加入文件柜'); }
function readFileDataURL(file){ return new Promise((res,rej)=>{ const r=new FileReader(); r.onerror=rej; r.onload=()=>res(r.result); r.readAsDataURL(file); }); }
function refreshFileList(){ const box=$('fileList'); if(!box) return; const q=($('fileSearch')?.value||'').toLowerCase().trim(); let list=getFiles(); if(q) list=list.filter(f=>[f.name,f.project,f.category,f.remark].some(v=>(v||'').toLowerCase().includes(q))); if(!list.length){ box.className='list empty'; box.textContent=q?'没搜到文件':'暂无文件'; return; } box.className='list'; box.innerHTML=''; list.forEach(f=>{ const div=document.createElement('div'); div.className='fileItem'; div.innerHTML=`<strong>${escapeHtml(f.name)}</strong><small>${escapeHtml(f.category)} ｜ ${escapeHtml(f.project||'未分项目')} ｜ ${formatSize(f.size)}</small><p>${escapeHtml(f.remark||'')}</p><div class="fileActions"><a class="toolLink" href="${f.data}" download="${escapeHtml(f.name)}">下载</a><button class="danger light" data-fdel="${f.id}">删除</button></div>`; box.appendChild(div); }); box.querySelectorAll('[data-fdel]').forEach(b=>b.onclick=()=>{ if(!confirm('删除这个文件？')) return; setFiles(getFiles().filter(x=>String(x.id)!==String(b.dataset.fdel))); }); }
function formatSize(n){ if(!n) return '0B'; if(n<1024) return n+'B'; if(n<1024*1024) return (n/1024).toFixed(1)+'KB'; return (n/1024/1024).toFixed(1)+'MB'; }

async function requestNotify(){ if('Notification' in window && Notification.permission==='default') return Notification.requestPermission(); }
function unlockAudio(){ try{ if(!alarmAudioCtx) alarmAudioCtx=new (window.AudioContext||window.webkitAudioContext)(); if(alarmAudioCtx.state==='suspended') alarmAudioCtx.resume(); }catch(e){} }
function startAlarmLoop(){ if(alarmInterval) clearInterval(alarmInterval); alarmTimeouts.forEach(t=>clearTimeout(t)); alarmTimeouts=[]; alarmInterval=setInterval(()=>checkAlarm(false),5000); scheduleTodayAlarms(); checkAlarm(true); }
function scheduleTodayAlarms(){ const s=getSettings(), map={[s.start]:'上班提醒',[s.middle]:'工作进行中提醒',[s.end]:'下班提醒'}; Object.keys(map).forEach(t=>{ const d=delayToTimeToday(t); if(d>0&&d<86400000) alarmTimeouts.push(setTimeout(()=>runAlarm(map[t],t),d)); }); }
function delayToTimeToday(t){ const [h,m]=t.split(':').map(Number), target=new Date(); target.setHours(h,m,0,0); return target.getTime()-Date.now(); }
function alarmMessage(title){ return title==='上班提醒'?'上班了，照片别漏。':title==='工作进行中提醒'?'中途补一张，免得像没干。':'下班前拍照归档，别空手回去。'; }
function checkAlarm(catchUp){ const s=getSettings(), now=timeNow(), map={[s.start]:'上班提醒',[s.middle]:'工作进行中提醒',[s.end]:'下班提醒'}; if(map[now]) runAlarm(map[now],now); if(catchUp){ const d=new Date(), cur=d.getHours()*60+d.getMinutes(); Object.entries(map).forEach(([t,title])=>{ const [h,m]=t.split(':').map(Number), mins=h*60+m; if(cur>=mins&&cur-mins<=2) runAlarm(title,t); }); } }
async function runAlarm(title,timeKey){ const key='xfx_v28_alarm_'+todayStr()+'_'+timeKey; if(localStorage.getItem(key)==='1') return; localStorage.setItem(key,'1'); const msg=alarmMessage(title); await fireNotification(title,msg); triggerAlarm(title,msg); }
async function fireNotification(title,body){ try{ if(!('Notification' in window)) return; if(Notification.permission==='default') await Notification.requestPermission(); if(Notification.permission!=='granted') return; const opt={body,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:'xfx-v28-alarm',renotify:true,requireInteraction:true,vibrate:[500,250,500,250,900]}; if(navigator.serviceWorker){ const reg=await navigator.serviceWorker.ready; if(reg?.showNotification){ await reg.showNotification(title,opt); return; } } new Notification(title,opt); }catch(e){} }
function triggerAlarm(title,text){ $('alarmTitle').textContent=title; $('alarmText').textContent=text; $('alarmOverlay').classList.remove('hidden'); playAlarm(); if(navigator.vibrate) navigator.vibrate([500,250,500,250,900,250,500]); }
function playAlarm(){ unlockAudio(); stopAlarmSoundOnly(); if(!alarmAudioCtx) return; [760,1280,1760].forEach((f,i)=>{ const osc=alarmAudioCtx.createOscillator(), gain=alarmAudioCtx.createGain(); osc.type=i===2?'square':'sine'; osc.frequency.value=f; gain.gain.value=i===2?0.055:0.08; osc.connect(gain); gain.connect(alarmAudioCtx.destination); osc.start(); alarmOsc.push(osc); }); const beat=()=>{ if(!alarmOsc.length) return; const t=alarmAudioCtx.currentTime; alarmOsc.forEach((osc,i)=>{ osc.frequency.setValueAtTime(i===0?760:i===1?1280:1760,t); osc.frequency.linearRampToValueAtTime(i===0?1260:i===1?780:960,t+.38); }); setTimeout(beat,650); }; beat(); }
function stopAlarmSoundOnly(){ alarmOsc.forEach(o=>{try{o.stop()}catch(e){}}); alarmOsc=[]; if(navigator.vibrate) navigator.vibrate(0); }
function stopAlarm(){ stopAlarmSoundOnly(); $('alarmOverlay').classList.add('hidden'); }
function registerSW(){ if('serviceWorker' in navigator){ navigator.serviceWorker.register('sw.js?v=28',{updateViaCache:'none'}).then(reg=>{ reg.update(); if(reg.waiting) reg.waiting.postMessage({type:'SKIP_WAITING'}); }).catch(()=>{}); } }

init();
